[workspace]
authors = ["Daniele Liprandi <daniele.liprandi@uni-greifswald.com>"]
channels = ["conda-forge"]
name = "VALKFlaskServer"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
flask = ">=3.1.2,<4"
sqlalchemy = ">=2.0.43,<3"
bcrypt = ">=4.3.0,<5"
requests = ">=2.32.5,<3"
apscheduler = ">=3.11.0,<4"
python-dateutil = ">=2.9.0.post0,<3"

[pypi-dependencies]
flask-sqlalchemy = ">=3.1.1, <4"
dotenv = ">=0.9.9, <0.10"
